name: build_fastdds

on:
  workflow_dispatch:
    inputs:
      fastdds_branch:
        description: 'Branch or tag of Fast DDS repository (https://github.com/eProsima/Fast-DDS)'
        required: true
        default: 'master'
      utils_branch:
        description: 'Branch or tag of Dev Utils repository (https://github.com/eProsima/dev-utils)'
        required: true
        default: 'main'
      ddsrouter_branch:
        description: 'Branch or tag of DDS Router repository (https://github.com/eProsima/DDS-Router)'
        required: true
        default: 'main'
  schedule:
    - cron: '0 0 * * *'


jobs:
  windows-build:
    runs-on: ${{ matrix.windows-version }}
    strategy:
      fail-fast: false
      matrix:
        cmake-config:
          - 'Release'
          - 'Debug'
        windows-version:
          - 'windows-2019'
          - 'windows-2022'
    env:
      CXXFLAGS: /MP
      OPENSSL64_ROOT: "C:/Program Files/OpenSSL-Win64"

    steps:
      - name: Sync eProsima/DDS-Recorder repository
        uses: actions/checkout@v2
        with:
          path: DDS-Recorder

      - name: Install OpenSSL
        uses: ./DDS-Recorder/.github/actions/install-openssl-windows

      - name: Install yaml-cpp
        uses: ./DDS-Recorder/.github/actions/install-yamlcpp-windows
        with:
          cmake_build_type: ${{ matrix.cmake-config }}

      - name: Install eProsima dependencies
        uses: ./DDS-Recorder/.github/actions/install-eprosima-dependencies-windows
        env:
          DEFAULT_FASTDDS_BRANCH: 'master'
          DEFAULT_UTILS_BRANCH: 'main'
          DEFAULT_DDSROUTER_BRANCH: 'main'
        with:
          cmake_build_type: ${{ matrix.cmake-config }}
          fastdds_branch: ${{ github.event.inputs.fastdds_branch || env.DEFAULT_FASTDDS_BRANCH }}
          utils_branch: ${{ github.event.inputs.utils_branch || env.DEFAULT_UTILS_BRANCH }}
          ddsrouter_branch: ${{ github.event.inputs.ddsrouter_branch || env.DEFAULT_DDSROUTER_BRANCH }}

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.windows-version }}_${{ matrix.cmake-config }}_fastdds_install
          path: ${{ github.workspace }}\eprosima\install

  ubuntu-build:
    runs-on: ${{ matrix.ubuntu-version }}
    strategy:
      fail-fast: false
      matrix:
        ubuntu-version:
          - 'ubuntu-20.04'
          - 'ubuntu-22.04'

    steps:
      - name: Sync eProsima/DDS-Recorder repository
        uses: actions/checkout@v2
        with:
          path: src/DDS-Recorder

      - name: Avoid DDS Recorder build
        run: |
          touch ./src/DDS-Recorder/COLCON_IGNORE

      - name: Install apt packages
        uses: ./src/DDS-Recorder/.github/actions/install-apt-packages

      - name: Install Python packages
        uses: ./src/DDS-Recorder/.github/actions/install-python-packages

      - name: Fetch repositories
        run: |
          vcs import src <  src/DDS-Recorder/.github/workflows/ci.repos
          cd src/fastrtps && git checkout ${{ inputs.fastdds_branch }} && cd ../..
          cd src/dev-utils && git checkout ${{ inputs.utils_branch }} && cd ../..
          cd src/ddsrouter && git checkout ${{ inputs.router_branch }} && cd ../..

      - name: Build workspace
        run: |
          colcon build --event-handlers=console_direct+

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.ubuntu-version }}_fastdds_install
          path: install
